name: MiracleGrow
description: Bukkit Minecraft plugin that tracks and restores blocks to keep your worlds looking fresh!
author: megabytes, verrier
website: http://minecarts.com/

main: com.minecarts.miraclegrow.MiracleGrow
version: ${pom.version}
depend: [DBQuery]

commands:
  miraclegrow:
    aliases: [mgrow]
    description: MiracleGrow internal commands
    usage: /<command> reload
    
permissions:
  miraclegrow:
    reload:
      description: Reload MiracleGrow config.yml
      default: op